# Generated by Django 2.2.24 on 2024-04-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('taxi_id', models.IntegerField()),
                ('customer_id', models.CharField(default='0', max_length=10)),
                ('pickup_point', models.CharField(default='0', max_length=1)),
                ('drop_point', models.CharField(default='0', max_length=1)),
                ('pickup_time', models.IntegerField()),
                ('drop_time', models.IntegerField()),
                ('pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('taxi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.TextField(default=[])),
                ('booking_id', models.TextField(default=[])),
                ('pickup_point', models.TextField(default=[1])),
                ('drop_point', models.TextField(default=[1])),
                ('pickup_time', models.TextField(default=[1])),
                ('drop_time', models.TextField(default=[1])),
                ('total_pay', models.IntegerField()),
            ],
        ),
    ]
